import { useEffect, useState } from 'react';
import { apiGet, apiPost, apiPut } from '../utils/api';

const blank = { name: '', code: '', description: '' };

const AdminDepartmentsPage = () => {
  const [departments, setDepartments] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const load = async () => { try { setLoading(true); setError(''); const data = await apiGet('/departments'); setDepartments(data.departments || []); } catch (e) { setError(e.message || 'Failed to load departments.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const reset = () => { setForm(blank); setEditing(null); };
  const save = async (event) => { event.preventDefault(); try { setSaving(true); setError(''); const payload = { ...form, name: form.name.trim(), code: form.code.trim().toUpperCase(), description: form.description.trim() }; const result = editing ? await apiPut(`/departments/${editing.id}`, payload) : await apiPost('/departments', payload); setSuccess(result.message); reset(); await load(); } catch (e) { setError(e.message || 'Failed to save department.'); } finally { setSaving(false); } };
  const changeStatus = async (department, action) => { try { setError(''); const result = await apiPut(`/departments/${department.id}/${action}`, {}); setSuccess(result.message); await load(); } catch (e) { setError(e.message || 'Failed to update department.'); } };
  if (loading) return <div className="card panel">Loading departments...</div>;
  return <div className="page-section"><div className="page-header"><div><p className="eyebrow">Administration</p><h2>Department Management</h2><p>Create, update, archive, and restore organizational departments.</p></div></div>{error && <div className="card panel error-box">{error}</div>}{success && <div className="card panel success-box">{success}</div>}<div className="card panel"><h3>{editing ? `Edit ${editing.name}` : 'Add Department'}</h3><form onSubmit={save} style={{display:'grid',gap:'.75rem',marginTop:'.75rem'}}><input required maxLength="120" value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} placeholder="Department name" aria-label="Department name"/><input required minLength="2" maxLength="50" pattern="[A-Za-z0-9_-]+" value={form.code} onChange={(e) => setForm({...form,code:e.target.value.toUpperCase()})} placeholder="Code, e.g. ENGINEERING" aria-label="Department code"/><textarea maxLength="255" value={form.description} onChange={(e) => setForm({...form,description:e.target.value})} placeholder="Description (optional)" aria-label="Department description"/><div style={{display:'flex',gap:'.5rem',flexWrap:'wrap'}}><button className="primary-btn" disabled={saving}>{saving ? 'Saving...' : editing ? 'Save changes' : 'Create department'}</button>{editing && <button type="button" className="secondary-btn" onClick={reset} disabled={saving}>Cancel</button>}</div></form></div><div className="card panel" style={{overflowX:'auto'}}><h3>Departments ({departments.length})</h3><table className="data-table"><thead><tr><th>Name</th><th>Code</th><th>Description</th><th>Employees</th><th>Status</th><th>Actions</th></tr></thead><tbody>{departments.length === 0 ? <tr><td colSpan="6">No departments configured.</td></tr> : departments.map((department) => <tr key={department.id}><td>{department.name}</td><td>{department.code}</td><td>{department.description || '--'}</td><td>{department.employee_count || 0}</td><td>{Number(department.is_active) ? 'Active' : 'Archived'}</td><td><div style={{display:'flex',gap:'.4rem',flexWrap:'wrap'}}><button className="secondary-btn small" onClick={() => { setEditing(department); setForm({name:department.name,code:department.code,description:department.description || ''}); }}>Edit</button><button className="secondary-btn small" onClick={() => changeStatus(department, Number(department.is_active) ? 'archive' : 'restore')}>{Number(department.is_active) ? 'Archive' : 'Restore'}</button></div></td></tr>)}</tbody></table></div></div>;
};

export default AdminDepartmentsPage;
