import { useEffect, useMemo, useState } from 'react';
import { apiGet, apiPut } from '../utils/api';

const AdminLeavesPage = () => {
  const [leaves, setLeaves] = useState([]); const [filter, setFilter] = useState('ALL'); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [actingId, setActingId] = useState(null); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const load = async () => { try { setLoading(true); setError(''); const data = await apiGet('/leaves/admin'); setLeaves(data.leaveRequests || []); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const decide = async (leave, status) => { let rejectionReason = ''; if (status === 'REJECTED') { rejectionReason = window.prompt('Why is this leave request being rejected?') || ''; if (!rejectionReason.trim()) return; } if (status === 'CANCELLED' && !window.confirm('Cancel this pending leave request?')) return; try { setActingId(leave.id); setError(''); const data = await apiPut(`/leaves/admin/${leave.id}/decision`, { status, ...(rejectionReason ? { rejection_reason: rejectionReason.trim() } : {}) }); setSuccess(data.message); setTimeout(() => setSuccess(''), 3000); await load(); } catch (err) { setError(err.message); } finally { setActingId(null); } };
  const shown = useMemo(() => { const search = query.trim().toLowerCase(); return leaves.filter((leave) => (filter === 'ALL' || leave.status === filter) && (!search || [leave.employee_name, leave.employee_code, leave.department, leave.leave_type].some((value) => String(value || '').toLowerCase().includes(search)))); }, [filter, leaves, query]);
  if (loading) return <div className="card panel">Loading leave data...</div>;
  return <div className="page-section"><div className="page-header"><div><p className="eyebrow">Leave Management</p><h2>Manage All Leave Requests</h2></div></div>{error && <div className="card panel error-box">{error}</div>}{success && <div className="card panel success-box">{success}</div>}<div className="metric-grid"><div className="metric-card card"><div className="label">Pending</div><div className="value">{leaves.filter((leave) => leave.status === 'PENDING').length}</div></div><div className="metric-card card"><div className="label">Approved</div><div className="value">{leaves.filter((leave) => leave.status === 'APPROVED').length}</div></div><div className="metric-card card"><div className="label">Total Days</div><div className="value">{leaves.reduce((total, leave) => total + Number(leave.total_days || 0), 0)}</div></div></div><div className="card panel" style={{display:'flex',gap:'.5rem',flexWrap:'wrap'}}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search employee, department, or type" style={{flex:'1 1 220px'}} />{['ALL','PENDING','APPROVED','REJECTED','CANCELLED'].map((status) => <button key={status} className={filter===status?'primary-btn small':'secondary-btn small'} onClick={() => setFilter(status)}>{status}</button>)}</div><div className="card panel" style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>Employee</th><th>Department</th><th>Type</th><th>Dates</th><th>Days</th><th>Status</th><th>Action</th></tr></thead><tbody>{shown.length===0?<tr><td colSpan="7" style={{textAlign:'center',padding:'2rem'}}>No leave requests found.</td></tr>:shown.map((leave) => <tr key={leave.id}><td>{leave.employee_name} ({leave.employee_code})</td><td>{leave.department||'--'}</td><td>{leave.leave_type}</td><td>{leave.start_date} to {leave.end_date}</td><td>{leave.total_days}</td><td>{leave.status}</td><td>{leave.status !== 'PENDING' ? '--' : <div style={{display:'flex',gap:'.4rem'}}><button className="secondary-btn small" disabled={actingId===leave.id} onClick={() => decide(leave,'APPROVED')}>Approve</button><button className="secondary-btn small" disabled={actingId===leave.id} onClick={() => decide(leave,'REJECTED')}>Reject</button><button className="secondary-btn small" disabled={actingId===leave.id} onClick={() => decide(leave,'CANCELLED')}>Cancel</button></div>}</td></tr>)}</tbody></table></div></div>;
};
export default AdminLeavesPage;
