import { useEffect, useState } from 'react';
import { apiGet, apiPost, apiPut } from '../utils/api';

const blank = { employee_id: '', month: 'January', year: new Date().getFullYear(), gross_salary: '', deductions: '' };
const AdminPayrollPage = () => {
  const [payslips, setPayslips] = useState([]); const [employees, setEmployees] = useState([]); const [form, setForm] = useState(blank);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const load = async () => { try { setLoading(true); setError(''); const [payroll, staff] = await Promise.all([apiGet('/payroll/admin'), apiGet('/payroll/admin/employees')]); setPayslips(payroll.payslips || []); setEmployees(staff.employees || []); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const notify = (message) => { setSuccess(message); setTimeout(() => setSuccess(''), 3000); };
  const create = async (event) => { event.preventDefault(); try { setSaving(true); const data = await apiPost('/payroll/admin', { ...form, employee_id: Number(form.employee_id), year: Number(form.year), gross_salary: Number(form.gross_salary), deductions: Number(form.deductions || 0) }); notify(data.message); setForm(blank); setShowForm(false); await load(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const publish = async (id) => { try { const data = await apiPut(`/payroll/admin/${id}`, { status: 'PUBLISHED' }); notify(data.message); await load(); } catch (err) { setError(err.message); } };
  if (loading) return <div className="card panel" style={{ padding: '2rem', textAlign: 'center' }}>Loading payroll data...</div>;
  const money = (value) => `₹${Number(value).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
  return <div className="page-section"><div className="page-header"><div><p className="eyebrow">Payroll Management</p><h2>Organization Payroll</h2></div><button className="primary-btn" onClick={() => setShowForm(!showForm)}>{showForm ? 'Cancel' : 'Create Payslip'}</button></div>
    {error && <div className="card panel error-box">{error}</div>}{success && <div className="card panel success-box">{success}</div>}
    {showForm && <div className="card panel"><h3>Create Draft Payslip</h3><form onSubmit={create} style={{ display: 'grid', gap: '1rem' }}><select required value={form.employee_id} onChange={(e) => setForm({ ...form, employee_id: e.target.value })}><option value="">Select employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name} ({employee.employee_code})</option>)}</select><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}><select value={form.month} onChange={(e) => setForm({ ...form, month: e.target.value })}>{['January','February','March','April','May','June','July','August','September','October','November','December'].map((month) => <option key={month}>{month}</option>)}</select><input type="number" min="2000" value={form.year} onChange={(e) => setForm({ ...form, year: e.target.value })} /></div><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}><input required type="number" min="0" step="0.01" placeholder="Gross salary" value={form.gross_salary} onChange={(e) => setForm({ ...form, gross_salary: e.target.value })} /><input type="number" min="0" step="0.01" placeholder="Deductions" value={form.deductions} onChange={(e) => setForm({ ...form, deductions: e.target.value })} /></div><button className="primary-btn" disabled={saving}>{saving ? 'Creating...' : 'Create Draft'}</button></form></div>}
    <div className="card panel"><h3>Payroll Details</h3><div style={{ overflowX: 'auto' }}><table className="data-table"><thead><tr><th>Employee</th><th>Period</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Status</th><th>Action</th></tr></thead><tbody>{payslips.length === 0 ? <tr><td colSpan="7" style={{ textAlign: 'center', padding: '2rem' }}>No payslips found.</td></tr> : payslips.map((p) => <tr key={p.id}><td>{p.employee_name}</td><td>{p.month} {p.year}</td><td>{money(p.gross_salary)}</td><td>{money(p.deductions)}</td><td>{money(p.net_salary)}</td><td>{p.status}</td><td>{p.status === 'DRAFT' ? <button className="secondary-btn small" onClick={() => publish(p.id)}>Publish</button> : '--'}</td></tr>)}</tbody></table></div></div>
  </div>;
};
export default AdminPayrollPage;
