import { useEffect, useState } from 'react';
import { apiGet, apiPut } from '../utils/api';

const AdminAttendanceManagementPage = () => {
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const [summary, setSummary] = useState(null); const [records, setRecords] = useState([]);
  const [department, setDepartment] = useState('ALL'); const [savingId, setSavingId] = useState(null);
  const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const load = async (value = date) => { try { setError(''); setSummary(null); const [summaryData, register] = await Promise.all([apiGet(`/attendance/admin/summary?date=${value}`), apiGet(`/attendance/admin/records?date=${value}`)]); setSummary(summaryData); setRecords(register.attendance || []); } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, []);
  const override = async (record, status) => { try { setSavingId(record.employee_id); const result = await apiPut(`/attendance/admin/records/${record.employee_id}`, { date, status }); setSuccess(result.message); setTimeout(() => setSuccess(''), 2500); await load(); } catch (err) { setError(err.message); } finally { setSavingId(null); } };
  const departments = [...new Set(records.map((record) => record.department || 'Unassigned'))]; const visible = department === 'ALL' ? records : records.filter((record) => (record.department || 'Unassigned') === department);
  return <div className="page-section"><div className="page-header"><div><p className="eyebrow">Attendance Management</p><h2>Organization Attendance</h2></div></div>{error && <div className="card panel error-box">{error}</div>}{success && <div className="card panel success-box">{success}</div>}<div className="card panel" style={{display:'flex',gap:'1rem',flexWrap:'wrap'}}><label><strong>Date</strong><input type="date" value={date} onChange={(event) => { setDate(event.target.value); load(event.target.value); }} /></label><label><strong>Department</strong><select value={department} onChange={(event) => setDepartment(event.target.value)}><option value="ALL">All departments</option>{departments.map((item) => <option key={item}>{item}</option>)}</select></label></div>{!summary ? <div className="card panel">Loading attendance...</div> : <><div className="card panel"><h3>Attendance Summary — {summary.date}</h3><div className="metric-grid">{[['Total Employees',summary.summary.total],['Present',summary.summary.present],['Absent',summary.summary.absent],['On Leave',summary.summary.onLeave],['Average Hours',`${summary.summary.avgHours}h`]].map(([label,value]) => <div className="metric-card card" key={label}><div className="label">{label}</div><div className="value">{value}</div></div>)}</div></div><div className="card panel" style={{overflowX:'auto'}}><h3>Daily Register</h3><table className="data-table"><thead><tr><th>Employee</th><th>Department</th><th>Check in</th><th>Hours</th><th>Status</th><th>Override</th></tr></thead><tbody>{visible.length === 0 ? <tr><td colSpan="6">No employees found.</td></tr> : visible.map((record) => <tr key={record.employee_id}><td>{record.employee_name} <small>({record.employee_code})</small></td><td>{record.department || '--'}</td><td>{record.check_in ? new Date(record.check_in).toLocaleTimeString() : '--'}</td><td>{record.working_hours || 0}</td><td>{record.status || 'ABSENT'}</td><td><div style={{display:'flex',gap:'.4rem',flexWrap:'wrap'}}>{['PRESENT','ABSENT','LATE'].map((status) => <button key={status} className="secondary-btn small" disabled={savingId === record.employee_id || record.status === status} onClick={() => override(record, status)}>{status}</button>)}</div></td></tr>)}</tbody></table></div></>}</div>;
};

export default AdminAttendanceManagementPage;
